language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 5.2
before_install:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --no-interaction --prefer-source
script: bin/phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover